// apps/nuxt-demo/app/components/ThemeModeSwitch.vue
<script setup lang="ts">
import type { Component } from "vue";
import type { ThemeName } from "@brustack/theme-transitions-core";
import IconDroplet from "./icons/IconDroplet.vue";
import IconMonitor from "./icons/IconMonitor.vue";
import IconMoon from "./icons/IconMoon.vue";
import IconSun from "./icons/IconSun.vue";

defineProps<{
  mode: ThemeName;
  disabled: boolean;
}>();

const emit = defineEmits<{
  select: [mode: ThemeName, event: MouseEvent];
}>();

const options: { value: ThemeName; label: string; icon: Component }[] = [
  { value: "system", label: "System", icon: IconMonitor },
  { value: "light", label: "Light", icon: IconSun },
  { value: "dark", label: "Dark", icon: IconMoon },
  { value: "sepia", label: "Sepia", icon: IconDroplet },
];
</script>

<template>
  <div class="mode-switch" role="group" aria-label="Theme mode">
    <button
      v-for="option in options"
      :key="option.value"
      type="button"
      class="mode-option"
      :class="{ active: mode === option.value }"
      :disabled="disabled || mode === option.value"
      @click="emit('select', option.value, $event)"
    >
      <component :is="option.icon" :size="16" aria-hidden="true" />
      {{ option.label }}
    </button>
  </div>
</template>

<style scoped>
.mode-switch {
  flex: 1;
  display: flex;
  gap: 1rem;
}

.mode-option {
  display: flex;
  align-items: center;
  gap: 0.35rem;
  font: inherit;
  font-size: 0.8125rem;
  font-weight: 600;
  color: var(--text-muted);
  background: none;
  border: none;
  border-bottom: 2px solid transparent;
  padding: 0 0 0.25rem;
  cursor: pointer;
  transition:
    color 0.15s,
    border-color 0.15s;
}

.mode-option:hover:not(:disabled):not(.active) {
  color: var(--text);
}

.mode-option.active {
  color: var(--text);
  border-bottom-color: var(--text);
}

.mode-option:disabled:not(.active) {
  opacity: 0.6;
  cursor: not-allowed;
}

.mode-option.active:disabled {
  cursor: default;
}
</style>

// apps/next-demo/app/components/ThemeModeSwitch.tsx
import type { ThemeName } from '@brustack/theme-transitions-core';
import { IconDroplet } from './icons/IconDroplet';
import { IconMonitor } from './icons/IconMonitor';
import { IconMoon } from './icons/IconMoon';
import { IconSun } from './icons/IconSun';
import './ThemeModeSwitch.css';

export interface ThemeModeSwitchProps {
	mode: ThemeName;
	disabled: boolean;
	onSelect: (mode: ThemeName, event: React.MouseEvent) => void;
}

const options: { value: ThemeName; label: string; Icon: typeof IconSun }[] = [
	{ value: 'system', label: 'System', Icon: IconMonitor },
	{ value: 'light', label: 'Light', Icon: IconSun },
	{ value: 'dark', label: 'Dark', Icon: IconMoon },
	{ value: 'sepia', label: 'Sepia', Icon: IconDroplet },
];

export const ThemeModeSwitch = ({ mode, disabled, onSelect }: ThemeModeSwitchProps) => (
	<div className="mode-switch" role="group" aria-label="Theme mode">
		{options.map(({ value, label, Icon }) => (
			<button
				key={value}
				type="button"
				className={`mode-option${mode === value ? ' active' : ''}`}
				disabled={disabled || mode === value}
				onClick={(event) => onSelect(value, event)}
			>
				<Icon size={16} aria-hidden="true" />
				{label}
			</button>
		))}
	</div>
);
